// UI-renderable field metadata. Mirrors the LLM extraction schemas so the
// review page can render every field generically.

import { CancerType } from '../types';

export type FieldKind = 'enum' | 'multi' | 'bool' | 'number';

export interface FieldDef {
  kind: FieldKind;
  label: string;
  options?: string[]; // for enum / multi
}

export interface SectionDef {
  key: string;          // e.g. "prostate", "matureBCell"
  cancerType: CancerType;
  label: string;
  fields: Record<string, FieldDef>;
}

const PRIOR = ['REQUIRED', 'EXCLUDED', 'EITHER'];
const POS_NEG = ['POSITIVE', 'NEGATIVE', 'EITHER'];
const POS_NEG_EQ = ['POSITIVE', 'NEGATIVE', 'EQUIVOCAL', 'EITHER'];
const STAGE_1_4 = ['I', 'II', 'III', 'IV'];

export const BASIC_FIELDS: Record<string, FieldDef> = {
  cancerTypes: {
    kind: 'multi', label: 'Cancer types accepted',
    options: [
      'PROSTATE','UROTHELIAL','RCC','TESTICULAR','BREAST','LUNG','COLORECTAL',
      'HEAD_AND_NECK','OVARIAN','UTERINE','CERVICAL','MELANOMA','MESOTHELIOMA',
      'GASTROESOPHAGEAL','NEUROENDOCRINE','PANCREATIC',
      'MATURE_B_CELL','MATURE_T_NK_CELL','MYELOID_NEOPLASM','PRECURSOR_LYMPHOID','PLASMA_CELL',
      'OTHER',
    ],
  },
  acceptsAllSolidTumors: { kind: 'bool', label: 'Basket / all solid tumors' },
  allowedSex: { kind: 'enum', label: 'Allowed sex', options: ['MALE', 'FEMALE', 'ALL'] },
  minAge: { kind: 'number', label: 'Min age (years)' },
  maxAge: { kind: 'number', label: 'Max age (years)' },
  ecogMin: { kind: 'number', label: 'ECOG min' },
  ecogMax: { kind: 'number', label: 'ECOG max' },
  previouslyUntreated: { kind: 'bool', label: 'Previously untreated required' },
};

export const SECTION_DEFS: SectionDef[] = [
  {
    key: 'prostate', cancerType: 'PROSTATE', label: 'Prostate',
    fields: {
      castrationStatus: { kind: 'enum', label: 'Castration status', options: ['SENSITIVE','RESISTANT','EITHER'] },
      metastaticStatus: { kind: 'enum', label: 'Metastatic status', options: ['METASTATIC','NON_METASTATIC','EITHER'] },
      metastaticSites: { kind: 'multi', label: 'Metastatic sites', options: ['BONE','VISCERAL','LYMPH_NODE'] },
      histology: { kind: 'enum', label: 'Histology', options: ['ADENOCARCINOMA','SMALL_CELL','NEUROENDOCRINE','EITHER'] },
      psmaStatus: { kind: 'enum', label: 'PSMA status', options: POS_NEG },
      hrrStatus: { kind: 'enum', label: 'HRR status', options: ['BRCA','NON_BRCA_HRR','NEGATIVE','EITHER'] },
      msiStatus: { kind: 'enum', label: 'MSI status', options: ['MSI_HIGH','MSS','EITHER'] },
      priorArpi: { kind: 'enum', label: 'Prior ARPI', options: PRIOR },
      priorTaxane: { kind: 'enum', label: 'Prior taxane', options: PRIOR },
      priorPsmaTherapy: { kind: 'enum', label: 'Prior PSMA therapy', options: PRIOR },
      priorParpi: { kind: 'enum', label: 'Prior PARPi', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'urothelial', cancerType: 'UROTHELIAL', label: 'Urothelial',
    fields: {
      site: { kind: 'multi', label: 'Site', options: ['BLADDER','UPPER_TRACT','URETHRAL'] },
      muscleInvasive: { kind: 'bool', label: 'Muscle invasive' },
      tStage: { kind: 'multi', label: 'T stage', options: ['Ta','Tis','T1','T2','T3','T4'] },
      nStage: { kind: 'multi', label: 'N stage', options: ['N0','N1','N2','N3'] },
      mStage: { kind: 'multi', label: 'M stage', options: ['M0','M1'] },
      highGrade: { kind: 'bool', label: 'High grade' },
      cisPresent: { kind: 'bool', label: 'CIS present' },
      bcgStatus: { kind: 'enum', label: 'BCG status', options: ['NAIVE','UNRESPONSIVE','EXPOSED','INTOLERANT','EITHER'] },
      fgfrStatus: { kind: 'enum', label: 'FGFR status', options: ['ALTERED','WILD_TYPE','EITHER'] },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      her2Status: { kind: 'enum', label: 'HER2 status', options: POS_NEG },
      cisplatinEligible: { kind: 'bool', label: 'Cisplatin eligible' },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      priorEnfortumab: { kind: 'enum', label: 'Prior enfortumab', options: PRIOR },
      priorCystectomy: { kind: 'enum', label: 'Prior cystectomy', options: PRIOR },
      histology: { kind: 'multi', label: 'Histology', options: ['UROTHELIAL','SQUAMOUS','NEUROENDOCRINE','SMALL_CELL','VARIANT'] },
    },
  },
  {
    key: 'rcc', cancerType: 'RCC', label: 'Renal cell carcinoma',
    fields: {
      histologySubtype: { kind: 'enum', label: 'Histology subtype', options: ['CLEAR_CELL','PAPILLARY','CHROMOPHOBE','NON_CLEAR_CELL','EITHER'] },
      sarcomatoidFeatures: { kind: 'bool', label: 'Sarcomatoid features' },
      metastaticStatus: { kind: 'enum', label: 'Metastatic status', options: ['METASTATIC','LOCALLY_ADVANCED','NON_METASTATIC','EITHER'] },
      imdcRisk: { kind: 'enum', label: 'IMDC risk', options: ['FAVORABLE','INTERMEDIATE','POOR','EITHER'] },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      priorNephrectomy: { kind: 'enum', label: 'Prior nephrectomy', options: PRIOR },
      priorTki: { kind: 'enum', label: 'Prior TKI', options: PRIOR },
      priorMetastaticImmunotherapy: { kind: 'enum', label: 'Prior metastatic IO', options: PRIOR },
      priorAdjuvantImmunotherapy: { kind: 'enum', label: 'Prior adjuvant IO', options: PRIOR },
      priorHif2aInhibitor: { kind: 'enum', label: 'Prior HIF2α inhibitor', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'testicular', cancerType: 'TESTICULAR', label: 'Testicular',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['SEMINOMA','NON_SEMINOMA','MIXED','EITHER'] },
      riskGroup: { kind: 'enum', label: 'Risk group', options: ['GOOD','INTERMEDIATE','POOR','EITHER'] },
      priorChemotherapy: { kind: 'enum', label: 'Prior chemotherapy', options: PRIOR },
      priorHdctAsct: { kind: 'enum', label: 'Prior HDCT/ASCT', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'breast', cancerType: 'BREAST', label: 'Breast',
    fields: {
      receptorSubtype: { kind: 'enum', label: 'Receptor subtype', options: ['HR_POS_HER2_NEG','HER2_POS','TRIPLE_NEGATIVE','EITHER'] },
      erStatus: { kind: 'enum', label: 'ER status', options: POS_NEG },
      her2Status: { kind: 'enum', label: 'HER2 status', options: POS_NEG_EQ },
      her2LowStatus: { kind: 'bool', label: 'HER2-low' },
      metastaticStatus: { kind: 'enum', label: 'Metastatic status', options: ['METASTATIC','LOCALLY_ADVANCED','EARLY_STAGE','EITHER'] },
      metastaticSites: { kind: 'multi', label: 'Metastatic sites', options: ['BONE','LIVER','LUNG','BRAIN','LYMPH_NODE'] },
      menopausalStatus: { kind: 'enum', label: 'Menopausal status', options: ['PRE','POST','EITHER'] },
      brcaStatus: { kind: 'enum', label: 'BRCA status', options: ['GERMLINE','SOMATIC','NEGATIVE','EITHER'] },
      esr1Status: { kind: 'enum', label: 'ESR1 status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      pik3caStatus: { kind: 'enum', label: 'PIK3CA status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      priorEndocrine: { kind: 'enum', label: 'Prior endocrine', options: PRIOR },
      priorCdk46Inhibitor: { kind: 'enum', label: 'Prior CDK4/6i', options: PRIOR },
      priorChemotherapy: { kind: 'enum', label: 'Prior chemotherapy', options: PRIOR },
      priorTrastuzumab: { kind: 'enum', label: 'Prior trastuzumab', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'lung', cancerType: 'LUNG', label: 'Lung',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['NSCLC','SCLC','EITHER'] },
      nsclcSubtype: { kind: 'enum', label: 'NSCLC subtype', options: ['ADENOCARCINOMA','SQUAMOUS','LARGE_CELL','EITHER'] },
      metastaticStatus: { kind: 'enum', label: 'Metastatic status', options: ['METASTATIC','LOCALLY_ADVANCED','EARLY_STAGE','EITHER'] },
      sclcExtent: { kind: 'enum', label: 'SCLC extent', options: ['LIMITED','EXTENSIVE','EITHER'] },
      brainMetastases: { kind: 'bool', label: 'Brain metastases' },
      egfrStatus: { kind: 'enum', label: 'EGFR status', options: ['CLASSICAL','EXON20_INS','UNCOMMON','WILD_TYPE','EITHER'] },
      alkStatus: { kind: 'enum', label: 'ALK status', options: ['REARRANGED','WILD_TYPE','EITHER'] },
      ros1Status: { kind: 'enum', label: 'ROS1 status', options: ['REARRANGED','WILD_TYPE','EITHER'] },
      krasStatus: { kind: 'enum', label: 'KRAS status', options: ['G12C','NON_G12C','WILD_TYPE','EITHER'] },
      brafStatus: { kind: 'enum', label: 'BRAF status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      metStatus: { kind: 'enum', label: 'MET status', options: ['AMPLIFIED','EXON_14_SKIPPING','WILD_TYPE','EITHER'] },
      retStatus: { kind: 'enum', label: 'RET status', options: ['REARRANGED','WILD_TYPE','EITHER'] },
      her2Status: { kind: 'enum', label: 'HER2 status', options: ['MUTATED','AMPLIFIED','WILD_TYPE','EITHER'] },
      pdl1Expression: { kind: 'enum', label: 'PD-L1 expression', options: ['HIGH','LOW','NEGATIVE','EITHER'] },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      priorTki: { kind: 'enum', label: 'Prior TKI', options: PRIOR },
      priorOsimertinib: { kind: 'enum', label: 'Prior osimertinib', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'colorectal', cancerType: 'COLORECTAL', label: 'Colorectal',
    fields: {
      site: { kind: 'enum', label: 'Site', options: ['COLON','RECTUM','EITHER'] },
      sidedness: { kind: 'enum', label: 'Sidedness', options: ['LEFT','RIGHT','EITHER'] },
      metastaticStatus: { kind: 'enum', label: 'Metastatic status', options: ['METASTATIC','LOCALLY_ADVANCED','EARLY_STAGE','EITHER'] },
      histology: { kind: 'enum', label: 'Histology', options: ['ADENOCARCINOMA','OTHER','EITHER'] },
      rasStatus: { kind: 'enum', label: 'RAS status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      krasg12cStatus: { kind: 'enum', label: 'KRAS G12C status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      brafStatus: { kind: 'enum', label: 'BRAF status', options: ['V600E','NON_V600E','WILD_TYPE','EITHER'] },
      msiStatus: { kind: 'enum', label: 'MSI status', options: ['MSI_HIGH','MSS','EITHER'] },
      her2Status: { kind: 'enum', label: 'HER2 status', options: POS_NEG },
      priorFluoropyrimidine: { kind: 'enum', label: 'Prior fluoropyrimidine', options: PRIOR },
      priorOxaliplatin: { kind: 'enum', label: 'Prior oxaliplatin', options: PRIOR },
      priorIrinotecan: { kind: 'enum', label: 'Prior irinotecan', options: PRIOR },
      priorAntiEgfr: { kind: 'enum', label: 'Prior anti-EGFR', options: PRIOR },
      priorAntiVegf: { kind: 'enum', label: 'Prior anti-VEGF', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      priorRegorafenibOrTas102: { kind: 'enum', label: 'Prior regorafenib or TAS-102', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'headAndNeck', cancerType: 'HEAD_AND_NECK', label: 'Head and neck',
    fields: {
      primarySite: { kind: 'enum', label: 'Primary site', options: ['ORAL_CAVITY','OROPHARYNX','LARYNX','HYPOPHARYNX','NASOPHARYNX','SALIVARY_GLAND','EITHER'] },
      hpvStatus: { kind: 'enum', label: 'HPV status', options: POS_NEG },
      p16Status: { kind: 'enum', label: 'p16 status', options: POS_NEG },
      tStage: { kind: 'multi', label: 'T stage', options: ['T1','T2','T3','T4'] },
      nStage: { kind: 'multi', label: 'N stage', options: ['N0','N1','N2','N3'] },
      mStage: { kind: 'multi', label: 'M stage', options: ['M0','M1'] },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      priorRadiation: { kind: 'enum', label: 'Prior radiation', options: PRIOR },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'ovarian', cancerType: 'OVARIAN', label: 'Ovarian',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['HIGH_GRADE_SEROUS','LOW_GRADE_SEROUS','MUCINOUS','CLEAR_CELL','ENDOMETRIOID','EITHER'] },
      figoStage: { kind: 'multi', label: 'FIGO stage', options: STAGE_1_4 },
      platinumSensitivity: { kind: 'enum', label: 'Platinum sensitivity', options: ['SENSITIVE','RESISTANT','REFRACTORY','EITHER'] },
      brcaStatus: { kind: 'enum', label: 'BRCA status', options: ['GERMLINE','SOMATIC','NEGATIVE','EITHER'] },
      hrdStatus: { kind: 'enum', label: 'HRD status', options: POS_NEG },
      priorDebulking: { kind: 'enum', label: 'Prior debulking', options: PRIOR },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorBevacizumab: { kind: 'enum', label: 'Prior bevacizumab', options: PRIOR },
      priorParpi: { kind: 'enum', label: 'Prior PARPi', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'uterine', cancerType: 'UTERINE', label: 'Uterine',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['ENDOMETRIOID','SEROUS','CARCINOSARCOMA','CLEAR_CELL','EITHER'] },
      figoStage: { kind: 'multi', label: 'FIGO stage', options: STAGE_1_4 },
      msiStatus: { kind: 'enum', label: 'MSI status', options: ['MSI_HIGH','MSS','EITHER'] },
      her2Status: { kind: 'enum', label: 'HER2 status', options: POS_NEG },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      p53Status: { kind: 'enum', label: 'p53 status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      priorRadiation: { kind: 'enum', label: 'Prior radiation', options: PRIOR },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'cervical', cancerType: 'CERVICAL', label: 'Cervical',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['SQUAMOUS','ADENOCARCINOMA','ADENOSQUAMOUS','EITHER'] },
      figoStage: { kind: 'multi', label: 'FIGO stage', options: STAGE_1_4 },
      hpvStatus: { kind: 'enum', label: 'HPV status', options: POS_NEG },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      priorChemoradiation: { kind: 'enum', label: 'Prior chemoradiation', options: PRIOR },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'melanoma', cancerType: 'MELANOMA', label: 'Melanoma',
    fields: {
      primarySite: { kind: 'enum', label: 'Primary site', options: ['CUTANEOUS','MUCOSAL','UVEAL','ACRAL','EITHER'] },
      stage: { kind: 'multi', label: 'Stage', options: STAGE_1_4 },
      brafStatus: { kind: 'enum', label: 'BRAF status', options: ['V600E','V600K','NON_V600','WILD_TYPE','EITHER'] },
      nrasStatus: { kind: 'enum', label: 'NRAS status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      kitStatus: { kind: 'enum', label: 'KIT status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      priorBrafMekInhibitor: { kind: 'enum', label: 'Prior BRAF/MEK inhibitor', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'mesothelioma', cancerType: 'MESOTHELIOMA', label: 'Mesothelioma',
    fields: {
      histology: { kind: 'enum', label: 'Histology', options: ['EPITHELIOID','SARCOMATOID','BIPHASIC','EITHER'] },
      primarySite: { kind: 'enum', label: 'Primary site', options: ['PLEURAL','PERITONEAL','EITHER'] },
      stage: { kind: 'multi', label: 'Stage', options: STAGE_1_4 },
      bap1Status: { kind: 'enum', label: 'BAP1 status', options: ['LOST','INTACT','EITHER'] },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorPemetrexed: { kind: 'enum', label: 'Prior pemetrexed', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'gastroesophageal', cancerType: 'GASTROESOPHAGEAL', label: 'Gastroesophageal',
    fields: {
      primarySite: { kind: 'enum', label: 'Primary site', options: ['GASTRIC','GEJ','ESOPHAGEAL','EITHER'] },
      histology: { kind: 'enum', label: 'Histology', options: ['ADENOCARCINOMA','SQUAMOUS','OTHER','EITHER'] },
      her2Status: { kind: 'enum', label: 'HER2 status', options: POS_NEG },
      pdl1Status: { kind: 'enum', label: 'PD-L1 status', options: POS_NEG },
      msiStatus: { kind: 'enum', label: 'MSI status', options: ['MSI_HIGH','MSS','EITHER'] },
      claudin18_2Status: { kind: 'enum', label: 'Claudin 18.2 status', options: POS_NEG },
      priorFluoropyrimidine: { kind: 'enum', label: 'Prior fluoropyrimidine', options: PRIOR },
      priorPlatinum: { kind: 'enum', label: 'Prior platinum', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      priorTrastuzumab: { kind: 'enum', label: 'Prior trastuzumab', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'neuroendocrine', cancerType: 'NEUROENDOCRINE', label: 'Neuroendocrine',
    fields: {
      primarySite: { kind: 'enum', label: 'Primary site', options: ['PANCREATIC','GI','LUNG','OTHER','EITHER'] },
      grade: { kind: 'enum', label: 'Grade', options: ['G1','G2','G3','EITHER'] },
      functionalStatus: { kind: 'enum', label: 'Functional status', options: ['FUNCTIONAL','NON_FUNCTIONAL','EITHER'] },
      somatostatinReceptorStatus: { kind: 'enum', label: 'SSTR status', options: POS_NEG },
      priorSomatostatinAnalog: { kind: 'enum', label: 'Prior SSA', options: PRIOR },
      priorChemotherapy: { kind: 'enum', label: 'Prior chemotherapy', options: PRIOR },
      priorPrrt: { kind: 'enum', label: 'Prior PRRT', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'pancreatic', cancerType: 'PANCREATIC', label: 'Pancreatic',
    fields: {
      resectability: { kind: 'enum', label: 'Resectability', options: ['RESECTABLE','BORDERLINE','LOCALLY_ADVANCED','METASTATIC','EITHER'] },
      histology: { kind: 'enum', label: 'Histology', options: ['ADENOCARCINOMA','OTHER','EITHER'] },
      krasStatus: { kind: 'enum', label: 'KRAS status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      brcaStatus: { kind: 'enum', label: 'BRCA status', options: ['GERMLINE','SOMATIC','NEGATIVE','EITHER'] },
      msiStatus: { kind: 'enum', label: 'MSI status', options: ['MSI_HIGH','MSS','EITHER'] },
      priorFolfirinox: { kind: 'enum', label: 'Prior FOLFIRINOX', options: PRIOR },
      priorGemcitabineNabpaclitaxel: { kind: 'enum', label: 'Prior gem/nab-paclitaxel', options: PRIOR },
      priorImmunotherapy: { kind: 'enum', label: 'Prior immunotherapy', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'matureBCell', cancerType: 'MATURE_B_CELL', label: 'Mature B-cell',
    fields: {
      acceptedDiseases: { kind: 'multi', label: 'Accepted diseases', options: ['DLBCL_NOS','HGBCL','HGBCL_DH_TH','PMBCL','DLBCL_LEG_TYPE','TCRBCL','TRANSFORMED_FL','TRANSFORMED_MZL','RICHTER','FL','MCL','MZL','CHL','CLL_SLL','WALDENSTROM','HCL','OTHER'] },
      cellOfOrigin: { kind: 'enum', label: 'Cell of origin', options: ['GCB','NON_GCB','ABC','EITHER'] },
      doubleHit: { kind: 'bool', label: 'Double hit' },
      follicularGrade: { kind: 'multi', label: 'Follicular grade', options: ['1_2','3A','3B'] },
      mantleCellVariant: { kind: 'multi', label: 'Mantle cell variant', options: ['CLASSICAL','BLASTOID','PLEOMORPHIC'] },
      ighvStatus: { kind: 'enum', label: 'IGHV status', options: ['MUTATED','UNMUTATED','EITHER'] },
      del17p: { kind: 'bool', label: 'del(17p)' },
      tp53Mutated: { kind: 'bool', label: 'TP53 mutated' },
      myd88Status: { kind: 'enum', label: 'MYD88 status', options: ['L265P','WILD_TYPE','EITHER'] },
      cxcr4Status: { kind: 'enum', label: 'CXCR4 status', options: ['MUTATED','WILD_TYPE','EITHER'] },
      cnsInvolvement: { kind: 'bool', label: 'CNS involvement' },
      cd19Positive: { kind: 'bool', label: 'CD19 positive' },
      cd20Positive: { kind: 'bool', label: 'CD20 positive' },
      cd22Positive: { kind: 'bool', label: 'CD22 positive' },
      stage: { kind: 'multi', label: 'Stage', options: STAGE_1_4 },
      transplantEligible: { kind: 'bool', label: 'Transplant eligible' },
      priorAntiCd20: { kind: 'enum', label: 'Prior anti-CD20', options: PRIOR },
      priorAntiCd19: { kind: 'enum', label: 'Prior anti-CD19', options: PRIOR },
      priorBtkInhibitor: { kind: 'enum', label: 'Prior BTKi', options: PRIOR },
      priorBcl2Inhibitor: { kind: 'enum', label: 'Prior BCL2i', options: PRIOR },
      priorAnthracycline: { kind: 'enum', label: 'Prior anthracycline', options: PRIOR },
      priorChemoimmunotherapy: { kind: 'enum', label: 'Prior chemoimmunotherapy', options: PRIOR },
      priorCarT: { kind: 'enum', label: 'Prior CAR-T', options: PRIOR },
      priorAutoTransplant: { kind: 'enum', label: 'Prior auto transplant', options: PRIOR },
      priorAlloTransplant: { kind: 'enum', label: 'Prior allo transplant', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'matureTnk', cancerType: 'MATURE_T_NK_CELL', label: 'Mature T/NK',
    fields: {
      acceptedDiseases: { kind: 'multi', label: 'Accepted diseases', options: ['PTCL_NOS','AITL','ALCL_ALK_POS','ALCL_ALK_NEG','CTCL_MF','CTCL_SS','NK_T','HSTCL','MEITL','EATL','ATL','OTHER'] },
      atlSubtype: { kind: 'multi', label: 'ATL subtype', options: ['ACUTE','LYMPHOMATOUS','CHRONIC','SMOLDERING'] },
      htlv1Status: { kind: 'enum', label: 'HTLV-1 status', options: POS_NEG },
      cd30Positive: { kind: 'bool', label: 'CD30 positive' },
      cd52Positive: { kind: 'bool', label: 'CD52 positive' },
      ccr4Positive: { kind: 'bool', label: 'CCR4 positive' },
      cnsInvolvement: { kind: 'bool', label: 'CNS involvement' },
      ctclStage: { kind: 'multi', label: 'CTCL stage', options: ['IA','IB','IIA','IIB','III','IVA','IVB'] },
      systemicStage: { kind: 'multi', label: 'Systemic stage', options: STAGE_1_4 },
      priorBrentuximab: { kind: 'enum', label: 'Prior brentuximab', options: PRIOR },
      priorMogamulizumab: { kind: 'enum', label: 'Prior mogamulizumab', options: PRIOR },
      priorChemotherapy: { kind: 'enum', label: 'Prior chemotherapy', options: PRIOR },
      priorRadiation: { kind: 'enum', label: 'Prior radiation', options: PRIOR },
      priorAutoTransplant: { kind: 'enum', label: 'Prior auto transplant', options: PRIOR },
      priorAlloTransplant: { kind: 'enum', label: 'Prior allo transplant', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'myeloid', cancerType: 'MYELOID_NEOPLASM', label: 'Myeloid',
    fields: {
      acceptedDiseases: { kind: 'multi', label: 'Accepted diseases', options: ['AML','MDS','CMML','MDS_MPN','MPN_PV','MPN_ET','MPN_MF','CML','OTHER'] },
      amlClassification: { kind: 'multi', label: 'AML classification', options: ['DE_NOVO','SECONDARY','THERAPY_RELATED'] },
      elnRisk: { kind: 'multi', label: 'ELN risk', options: ['FAVORABLE','INTERMEDIATE','ADVERSE'] },
      flt3Status: { kind: 'enum', label: 'FLT3 status', options: ['ITD','TKD','WILD_TYPE','EITHER'] },
      npm1Mutated: { kind: 'bool', label: 'NPM1 mutated' },
      idh1Mutated: { kind: 'bool', label: 'IDH1 mutated' },
      idh2Mutated: { kind: 'bool', label: 'IDH2 mutated' },
      ipssR: { kind: 'multi', label: 'IPSS-R', options: ['VERY_LOW','LOW','INT','HIGH','VERY_HIGH'] },
      ipssM: { kind: 'multi', label: 'IPSS-M', options: ['VERY_LOW','LOW','MODERATE_LOW','MODERATE_HIGH','HIGH','VERY_HIGH'] },
      minBlastsPercent: { kind: 'number', label: 'Min blasts (%)' },
      maxBlastsPercent: { kind: 'number', label: 'Max blasts (%)' },
      ringSideroblasts: { kind: 'bool', label: 'Ring sideroblasts' },
      sf3b1Mutated: { kind: 'bool', label: 'SF3B1 mutated' },
      jak2Status: { kind: 'enum', label: 'JAK2 status', options: ['V617F','EXON12','WILD_TYPE','EITHER'] },
      calrMutated: { kind: 'bool', label: 'CALR mutated' },
      mplMutated: { kind: 'bool', label: 'MPL mutated' },
      bcrAblStatus: { kind: 'enum', label: 'BCR-ABL status', options: POS_NEG },
      cmlPhase: { kind: 'multi', label: 'CML phase', options: ['CHRONIC','ACCELERATED','BLAST'] },
      complexKaryotype: { kind: 'bool', label: 'Complex karyotype' },
      monosomy7: { kind: 'bool', label: 'Monosomy 7' },
      tp53Mutated: { kind: 'bool', label: 'TP53 mutated' },
      maxWhiteBloodCount: { kind: 'number', label: 'Max WBC' },
      hlaA0201Required: { kind: 'bool', label: 'HLA-A*02:01 required' },
      cnsInvolvement: { kind: 'bool', label: 'CNS involvement' },
      priorHma: { kind: 'enum', label: 'Prior HMA', options: PRIOR },
      priorVenetoclax: { kind: 'enum', label: 'Prior venetoclax', options: PRIOR },
      priorIntensiveChemotherapy: { kind: 'enum', label: 'Prior intensive chemo', options: PRIOR },
      priorFlt3Inhibitor: { kind: 'enum', label: 'Prior FLT3i', options: PRIOR },
      priorIdhInhibitor: { kind: 'enum', label: 'Prior IDHi', options: PRIOR },
      priorJakInhibitor: { kind: 'enum', label: 'Prior JAKi', options: PRIOR },
      priorBcrAblTki: { kind: 'enum', label: 'Prior BCR-ABL TKI', options: PRIOR },
      priorAlloTransplant: { kind: 'enum', label: 'Prior allo transplant', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'precursorLymphoid', cancerType: 'PRECURSOR_LYMPHOID', label: 'Precursor lymphoid',
    fields: {
      acceptedDiseases: { kind: 'multi', label: 'Accepted diseases', options: ['B_ALL','T_ALL','LBL_B','LBL_T','OTHER'] },
      philadelphiaStatus: { kind: 'enum', label: 'Philadelphia status', options: ['POSITIVE','NEGATIVE','PH_LIKE','EITHER'] },
      cd19Positive: { kind: 'bool', label: 'CD19 positive' },
      cd22Positive: { kind: 'bool', label: 'CD22 positive' },
      cd7Positive: { kind: 'bool', label: 'CD7 positive' },
      mrdStatus: { kind: 'enum', label: 'MRD status', options: POS_NEG },
      cnsStatus: { kind: 'multi', label: 'CNS status', options: ['CNS1','CNS2','CNS3'] },
      minRelapseNumber: { kind: 'number', label: 'Min relapse #' },
      maxRelapseNumber: { kind: 'number', label: 'Max relapse #' },
      priorBlinatumomab: { kind: 'enum', label: 'Prior blinatumomab', options: PRIOR },
      priorInotuzumab: { kind: 'enum', label: 'Prior inotuzumab', options: PRIOR },
      priorCarT: { kind: 'enum', label: 'Prior CAR-T', options: PRIOR },
      priorBcrAblTki: { kind: 'enum', label: 'Prior BCR-ABL TKI', options: PRIOR },
      priorAlloTransplant: { kind: 'enum', label: 'Prior allo transplant', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
  {
    key: 'plasmaCell', cancerType: 'PLASMA_CELL', label: 'Plasma cell',
    fields: {
      acceptedDiseases: { kind: 'multi', label: 'Accepted diseases', options: ['MM','PCL','PLASMACYTOMA','AL_AMYLOIDOSIS','WALDENSTROM_LPL','POEMS','OTHER'] },
      issStage: { kind: 'multi', label: 'ISS stage', options: ['I','II','III'] },
      rissStage: { kind: 'multi', label: 'R-ISS stage', options: ['I','II','III'] },
      highRiskCytogenetics: { kind: 'bool', label: 'High-risk cytogenetics' },
      del17p: { kind: 'bool', label: 'del(17p)' },
      t4_14: { kind: 'bool', label: 't(4;14)' },
      t14_16: { kind: 'bool', label: 't(14;16)' },
      gain1q: { kind: 'bool', label: '1q gain' },
      measurableDiseaseImwg: { kind: 'bool', label: 'Measurable disease (IMWG)' },
      extramedullaryDisease: { kind: 'bool', label: 'Extramedullary disease' },
      cnsInvolvement: { kind: 'bool', label: 'CNS involvement' },
      amyloidOrganInvolvement: { kind: 'multi', label: 'Amyloid organ involvement', options: ['CARDIAC','RENAL','HEPATIC','NEURO','GI'] },
      mayoStage: { kind: 'multi', label: 'Mayo stage', options: ['I','II','III','IIIA','IIIB'] },
      priorImid: { kind: 'enum', label: 'Prior IMiD', options: PRIOR },
      priorProteasomeInhibitor: { kind: 'enum', label: 'Prior PI', options: PRIOR },
      priorAntiCd38: { kind: 'enum', label: 'Prior anti-CD38', options: PRIOR },
      priorBcmaTherapy: { kind: 'enum', label: 'Prior BCMA therapy', options: PRIOR },
      priorAutoTransplant: { kind: 'enum', label: 'Prior auto transplant', options: PRIOR },
      priorAlloTransplant: { kind: 'enum', label: 'Prior allo transplant', options: PRIOR },
      maxPriorRegimens: { kind: 'number', label: 'Max prior regimens' },
    },
  },
];

export const SECTION_BY_KEY: Record<string, SectionDef> =
  Object.fromEntries(SECTION_DEFS.map((s) => [s.key, s]));

export const SECTION_BY_CANCER_TYPE: Partial<Record<CancerType, SectionDef>> =
  Object.fromEntries(SECTION_DEFS.map((s) => [s.cancerType, s])) as Partial<Record<CancerType, SectionDef>>;
